name: Update TODO.md
on:
    push:
      branches:
        - "master"

jobs:
  generate-todo:
    name: Update TODO.md
    runs-on: ubuntu-latest

    env:
      working-directory: .
      leasot-cmd: npx leasot -x --reporter markdown 'src/**/*.ts' 'src/**/*.js'
      todo-filename: ./TODO.md

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Setup NodeJS
      uses: actions/setup-node@v2
      with:
        node-version: "14" # until all NodeJS 15 build issues are sorted
    - name: Run leasot
      working-directory: ${{env.working-directory}}
      run: |
        ${{env.leasot-cmd}} > ${{env.todo-filename}}
    - name: Commit changes
      id: commit
      uses: EndBug/add-and-commit@v7
      with:
        default_author: github_actions
        message: "chore: update ${{env.todo-filename}}"
        add: ${{env.working-directory}}/${{env.todo-filename}}